# Generated by Django 3.0.6 on 2020-05-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Complete', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('Id_Number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Id_Type', models.CharField(choices=[('PASSPT', 'PassPort'), ('NNUMBER', 'National Number'), ('NCARD', 'National Card')], default='NNUMBER', max_length=7)),
                ('Full_Name', models.CharField(max_length=30)),
                ('Date_Of_Birth', models.DateField()),
                ('Place_Of_Birth', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('ML', 'male'), ('FM', 'female')], default='ML', max_length=2)),
                ('Social_Status', models.CharField(choices=[('Single', 'single'), ('Married', 'married'), ('Divorced', 'divorced'), ('Widowed', 'widowed')], default='ML', max_length=8)),
                ('Education_Level', models.CharField(max_length=10)),
                ('Job_Title', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('House_Number', models.PositiveIntegerField()),
                ('Family_Members_Number', models.PositiveIntegerField()),
                ('Task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_Name', models.CharField(max_length=20)),
                ('Family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Family')),
            ],
            options={
                'ordering': ['Area_Name'],
            },
        ),
    ]
