# Generated by Django 3.0.6 on 2020-05-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='Task',
        ),
        migrations.AddField(
            model_name='task',
            name='Family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Family'),
        ),
    ]
