# Generated by Django 3.0.6 on 2020-06-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200531_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Quantity',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
