# Generated by Django 3.0.6 on 2020-06-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200602_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['Created']},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Area')),
            ],
            options={
                'ordering': ['Created'],
            },
        ),
    ]
