# Generated by Django 3.0.6 on 2020-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200606_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
