# Generated by Django 3.0.6 on 2020-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200606_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-Created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-Created']},
        ),
        migrations.AddField(
            model_name='project',
            name='Project_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
