# Generated by Django 3.0.6 on 2020-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200607_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
