# Generated by Django 3.0.6 on 2020-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
