# Generated by Django 3.0.6 on 2020-06-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Family'),
        ),
    ]
