# Generated by Django 3.0.6 on 2020-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_familymember_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='family',
            name='Social_Status',
            field=models.CharField(choices=[('Single', 'single'), ('Married', 'married'), ('Divorced', 'divorced'), ('Widowed', 'widowed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
    ]
